@startuml 01-di
namespace backend {
    class LevelDB {
        mdb *memdb.DB
        Insert(k []byte, v []byte) error
        FindByID(k []byte) ([]byte, error)
    }
    class Client {
        backend Storer
        Insert(k []byte, v []byte) error
        FindByID(k []byte) ([]byte, error)

    }
    interface Storer  {
        Insert(k []byte, v []byte) error
        FindByID(k []byte) ([]byte, error)

    }
}
namespace backend_test {
    class TestBackend  {
        kv <font color=blue>map</font>[string][]byte
        Insert(k []byte, v []byte) error
        FindByID(k []byte) ([]byte, error)
    }
}

backend.Client --> backend.Storer : uses
backend.Storer <|-- backend.LevelDB : implements
backend.Storer <|-- backend_test.TestBackend : implements

@enduml
